/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/PZEUK21WTPE
 */
import { CollapsibleTrigger, CollapsibleContent, Collapsible } from "@/components/ui/collapsible"
import { Button } from "@/components/ui/button"
import { Link } from "react-router-dom";

export default function Detailspage() {
  return (
    (<div key="1" className="flex flex-col gap-6 p-6 my-12 mx-14">
      <div className="flex items-center justify-between mb-4">
        <h1 className="text-4xl font-bold">Operating System</h1>
        <p className="text-xl font-semibold">Total Duration: 9 weeks</p>
      </div>
      <hr className="border-2 border-gray-500 dark:border-gray-800 mb-" />
      <Collapsible className="border border-gray-200 rounded-lg dark:border-gray-800">
        <CollapsibleTrigger asChild>
          <div className="flex items-center justify-between p-4">
            <div className="flex items-center gap-4">
              <h2 className="text-xl font-semibold">Unit 1: Introduction</h2>
              <p className="text-sm font-medium text-gray-900 dark:text-gray-50">Duration: 2 weeks</p>
            </div>
            <ChevronDownIcon className="w-5 h-5 text-gray-500 dark:text-gray-400" />
          </div>
        </CollapsibleTrigger>
        <CollapsibleContent>
          <div className="flex justify-start gap-2 p-4">
            <Link to="/practicepage"><Button
            className="inline-flex items-center gap-2 text-sm font-medium bg-blue-500 text-white w-[150px]"
            download
            href="/unit-1.pdf">
            Practice Questions
          </Button></Link>
          <Link to="/quizpage">  <Button
          className="inline-flex items-center gap-2 text-sm font-medium bg-blue-500 text-white w-[150px]"
          href="/unit-1-quiz">
          Quiz
        </Button></Link>
          </div>
        </CollapsibleContent>
      </Collapsible>
      <Collapsible className="border border-gray-200 rounded-lg dark:border-gray-800">
        <CollapsibleTrigger asChild>
          <div className="flex items-center justify-between p-4">
            <div className="flex items-center gap-4">
              <h2 className="text-xl font-semibold">Unit 2: Basics</h2>
              <p className="text-sm font-medium text-gray-900 dark:text-gray-50">Duration: 3 weeks</p>
            </div>
            <ChevronDownIcon className="w-5 h-5 text-gray-500 dark:text-gray-400" />
          </div>
        </CollapsibleTrigger>
        <CollapsibleContent>
          <div className="flex justify-start gap-2 p-4">
            <Button
              className="inline-flex items-center gap-2 text-sm font-medium bg-blue-500 text-white w-[150px]"
              download
              href="/unit-2.pdf">
              Practice Questions
            </Button>
            <Button
              className="inline-flex items-center gap-2 text-sm font-medium bg-blue-500 text-white w-[150px]"
              href="/unit-2-quiz">
              Quiz
            </Button>
          </div>
        </CollapsibleContent>
      </Collapsible>
      <Collapsible className="border border-gray-200 rounded-lg dark:border-gray-800">
        <CollapsibleTrigger asChild>
          <div className="flex items-center justify-between p-4">
            <div className="flex items-center gap-4">
              <h2 className="text-xl font-semibold">Unit 3: Advanced Topics</h2>
              <p className="text-sm font-medium text-gray-900 dark:text-gray-50">Duration: 4 weeks</p>
            </div>
            <ChevronDownIcon className="w-5 h-5 text-gray-500 dark:text-gray-400" />
          </div>
        </CollapsibleTrigger>
        <CollapsibleContent>
          <div className="flex justify-start gap-2 p-4">
            <Button
              className="inline-flex items-center gap-2 text-sm font-medium bg-blue-500 text-white w-[150px]"
              download
              href="/unit-3.pdf">
              Practice Questions
            </Button>
            <Button
              className="inline-flex items-center gap-2 text-sm font-medium bg-blue-500 text-white w-[150px]"
              href="/unit-3-quiz">
              Quiz
            </Button>
          </div>
        </CollapsibleContent>
      </Collapsible>
    </div>)
  );
}


function ChevronDownIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="m6 9 6 6 6-6" />
    </svg>)
  );
}
