/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/f0pv9phvzRP
 */

import { CardTitle, CardHeader, CardContent, CardFooter, Card } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import { useState,useEffect } from "react";
import Navbar from "@/components/ui/Navbar";
import { Link } from 'react-router-dom';
import CreateClassroom from "@/components/ui/CreateClassroom";
import { Swiper, SwiperSlide } from "swiper/react";
// Import Swiper styles
import "swiper/css";
import "swiper/css/pagination";
import { Pagination } from "swiper/modules";
import { Progress } from "@/components/ui/progress";


const calculateSlidesPerView = () => {
  const windowWidth = window.innerWidth;

  if (windowWidth >= 1024) {
    return 3;
  } else if (windowWidth >= 768) {
    return 2;
  } else {
    return 1;
  }
};
 export default function Adminpage({classes}) {
  const [slidesPerView, setSlidesPerView] = useState(calculateSlidesPerView());
  const [courseList, setCourseList] = useState(classes);
  useEffect(() => {
    const handleResize = () => {
      setSlidesPerView(calculateSlidesPerView());
    };

    window.addEventListener("resize", handleResize);

    return () => {
      window.removeEventListener("resize", handleResize);
    };
  }, []);
  return (
    (<div key="1" className="bg-gray-100 min-h-screen">
    <Navbar name="Admin Dashboard" />
      <main className="px-4 py-5 sm:p-6">
        <section className="mb-8" id="managecourses">
        <div className="flex justify-between items-center mb-4">
          <h2 className="mb-2 text-2xl font-bold leading-6 text-gray-900 mb-4">Manage Courses</h2>
          <Link to = "/classroom">
            {" "}
          <Button className=" leading-6 bg-[#040404] text-[#B3CCC2]">Create New</Button>
          </Link>
          </div>
          {/* <div className="grid grid-cols-3 gap-6"> */}
            
           <Swiper
                pagination={true}
                modules={[Pagination]}
                className="mySwiper p-3"
                slidesPerView={slidesPerView}
                spaceBetween={30}
              >
                {classes.map((course) => (
              
               <SwiperSlide className=" rounded-[50px]" key={course.id}> 
            <Card className="w-full shadow-lg  rounded-[30px]">
              <CardHeader>
                <CardTitle>{course.title}</CardTitle>
              </CardHeader>
              <CardFooter className="flex justify-center mt-4">
                <Link to = "/viewclassroom">
                  {""}
                <Button className=" mr-20 bg-[#040404] text-[#B3CCC2] hover:bg-[#B3CCC2] hover:text-[#040404]"
                >View</Button>
                </Link>
                <Button variant="destructive" className="ml-20">
                Delete</Button>
              </CardFooter>
            </Card>
            </SwiperSlide>
          ))} 
               </Swiper> 
        </section>
      </main>
    </div>)


   );
 }


