/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/WYsv0xX5tNY
 */
import {
  CardTitle,
  CardDescription,
  CardHeader,
  CardContent,
  Card,
} from "@/components/ui/card";
import { AvatarImage, AvatarFallback, Avatar } from "@/components/ui/avatar";
import {
  DropdownMenuTrigger,
  DropdownMenuLabel,
  DropdownMenuSeparator,
  DropdownMenuItem,
  DropdownMenuContent,
  DropdownMenu,
} from "@/components/ui/dropdown-menu";
import Logo from "../../../assets/Logo/logo.png";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import {
  SelectValue,
  SelectTrigger,
  SelectItem,
  SelectContent,
  Select,
} from "@/components/ui/select";

export default function Professorui() {
  return (
    <div className="flex flex-col h-screen bg-gray-100 dark:bg-gray-800">
      <div className="flex flex-1 overflow-hidden">
        <aside className="w-16 bg-[#040404] min-h-screen flex flex-col items-center py-4 space-y-4 px-24">
          <div className="flex flex-col items-center">
            <img
              className="h-36 w-48 object-cover border rounded-[50%] border-[#82717c] cursor-pointer"
              src={Logo}
              alt=""
            />
            <div className="flex flex-col justify-start gap-6 mt-8 scroll-smooth">
              <a
                className="flex items-center gap-2 px-3 py-2 text-white rounded dark:hover:bg-gray-700"
                href="#studentdetails"
              >
                <span className="text-[#A8ABBA]  hover:text-[#ECF0F1]">
                  Home
                </span>
              </a>
              <a
                className="flex items-center gap-2 px-3 py-2 text-white rounded dark:hover:bg-gray-700"
                href="#completedcourses"
              >
                <span className="text-[#A8ABBA]  hover:text-[#ECF0F1]">
                  Syllabus
                </span>
              </a>

              <a
                className="flex items-center gap-2 px-3 py-2 text-white rounded dark:hover:bg-gray-700"
                href="#upcomingassessments"
              >
                <span className="text-[#A8ABBA]  hover:text-[#ECF0F1]">
                  Courses
                </span>
              </a>

              <a
                className="flex items-center gap-2 px-3 py-2 text-white rounded dark:hover:bg-gray-700"
                href="#analyticsboard"
              >
                <span className="text-[#A8ABBA] hover:text-[#ECF0F1]">
                  Assessments
                </span>
              </a>
            </div>
          </div>
        </aside>

        <main className="flex-1 p-4 overflow-auto bg-[#fff] text-[#040404]">
          <header className="flex items-center h-16 mb-8 dark:bg-gray-900">
            <nav className="flex items-center justify-between w-full">
              <div className="flex items-center space-x-4">
                <span className="text-xl font-semibold px-32 py-2 bg-[#040404] text-[#B3CCC2] rounded-md ">
                  Professor Dashboard
                </span>
              </div>
              <DropdownMenu>
                <DropdownMenuTrigger asChild>
                  <Avatar className="h-9 w-9">
                    <AvatarImage
                      alt="User avatar"
                      src="https://imgs.search.brave.com/J0ixr3aHGA8aitBrET8u4exc5KcrQl8PWXGrvAdsUY4/rs:fit:500:0:0/g:ce/aHR0cHM6Ly9mcmVl/c3ZnLm9yZy9pbWcv/YWJzdHJhY3QtdXNl/ci1mbGF0LTQucG5n"
                    />
                  </Avatar>
                </DropdownMenuTrigger>
                <DropdownMenuContent>
                  <DropdownMenuSeparator />
                  <DropdownMenuItem>
                    <a className="flex items-center gap-2" href="#">
                      <UserIcon className="w-4 h-4" />
                      John Doe
                    </a>
                  </DropdownMenuItem>
                  <DropdownMenuItem>
                    <a className="flex items-center gap-2" href="#">
                      <MailIcon className="w-4 h-4" />
                      ums@gmail.com
                    </a>
                  </DropdownMenuItem>
                  <DropdownMenuSeparator />
                  <DropdownMenuItem>
                    <a className="flex items-center gap-2" href="#">
                      <LogOutIcon className="w-4 h-4" />
                      Logout
                    </a>
                  </DropdownMenuItem>
                </DropdownMenuContent>
              </DropdownMenu>
            </nav>
          </header>

          <section className="mb-8" id="studentdetails">
            <h2 className="mb-2 text-2xl font-bold">Professor Details</h2>

            <div className="grid grid-cols-1 gap-2 md:grid-cols-2">
              <Card className="p-2 bg-[#ECF0F1] shadow-lg flex justify-between items-center">
                <div>
                  <CardHeader>
                    <CardTitle> Prof. John Doe</CardTitle>
                  </CardHeader>
                  <CardContent>
                    <div className="grid gap-1">
                      <div>
                        <span className="text-[#111129] font-bold">
                          Department
                        </span>
                        : Computer Science
                      </div>
                      <div>
                        <span className="text-[#111129] font-bold">
                          Subjects
                        </span>
                        : Mathematics, DLD
                      </div>
                    </div>
                  </CardContent>
                </div>
                <div className="w-[100px] h-[100px] mx-20">
                  <img
                    src="https://imgs.search.brave.com/J0ixr3aHGA8aitBrET8u4exc5KcrQl8PWXGrvAdsUY4/rs:fit:500:0:0/g:ce/aHR0cHM6Ly9mcmVl/c3ZnLm9yZy9pbWcv/YWJzdHJhY3QtdXNl/ci1mbGF0LTQucG5n"
                    alt=""
                  />
                </div>
              </Card>
            </div>
          </section>
        </main>
      </div>
    </div>
  );
}

function CheckIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <polyline points="20 6 9 17 4 12" />
    </svg>
  );
}

function UserIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M19 21v-2a4 4 0 0 0-4-4H9a4 4 0 0 0-4 4v2" />
      <circle cx="12" cy="7" r="4" />
    </svg>
  );
}

function MailIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect width="20" height="16" x="2" y="4" rx="2" />
      <path d="m22 7-8.97 5.7a1.94 1.94 0 0 1-2.06 0L2 7" />
    </svg>
  );
}

function LogOutIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M9 21H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h4" />
      <polyline points="16 17 21 12 16 7" />
      <line x1="21" x2="9" y1="12" y2="12" />
    </svg>
  );
}
