/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/WYsv0xX5tNY
 */
import {
  CardTitle,
  CardDescription,
  CardHeader,
  CardContent,
  Card,
} from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import {
  SelectValue,
  SelectTrigger,
  SelectItem,
  SelectContent,
  Select,
} from "@/components/ui/select";

export default function Professorui() {
  return (
    <>
      <div className="bg-[#e6f7ff] min-h-screen">
        <header className="bg-[#3399ff] p-4 text-white">
          <div className="container mx-auto flex justify-between items-center px-4 md:px-8 lg:px-16">
            <h1 className="text-2xl font-bold">Professor Portal</h1>
            <nav>
              <ul className="flex space-x-4 justify-end">
                <li>
                  <a className="block hover:text-gray-200" href="#">
                    Home
                  </a>
                </li>
                <li>
                  <a className="block hover:text-gray-200" href="#">
                    Academics
                  </a>
                </li>
                <li>
                  <a className="block hover:text-gray-200" href="#">
                    Placement
                  </a>
                </li>
                <li>
                  <a className="block hover:text-gray-200" href="#">
                    College
                  </a>
                </li>
                <li>
                  <a className="block hover:text-gray-200" href="#">
                    Contact
                  </a>
                </li>
              </ul>
            </nav>
          </div>
        </header>
        <main className="p-4 px-4 md:px-8 lg:px-16">
          <section className="mb-6">
            <h2 className="text-xl font-bold mb-4">Professor Details :</h2>
            <div className="flex">
              <Card className="bg-white  shadow-">
                <CardHeader>
                  <CardTitle>John Doe</CardTitle>
                  <CardDescription>Professor</CardDescription>
                </CardHeader>
                <CardContent>
                  <div className="grid gap-1">
                    <div>Department : Computer Science</div>
                    <div>Subjects : OS,CN</div>
                  </div>
                </CardContent>
              </Card>
            </div>
          </section>
          <section className="mb-6">
            <h2 className="text-xl font-semibold mb-2">Courses</h2>
            <div className="grid grid-cols-4 gap-4">
              <Card className="bg-white p-4 shadow-lg">
                <CardHeader>
                  <CardTitle>Data Structures and Algorithms</CardTitle>
                  <CardDescription>Due on: 30th Jan 2024</CardDescription>
                </CardHeader>
                <Button className="mt-4 bg-[#3399ff] text-white hover:bg-blue-500">{`Topics->`}</Button>
              </Card>
              <Card className="bg-white p-4 shadow-lg">
                <CardHeader className="flex justify-between items-center">
                  <div>
                    <CardTitle>Computer Networks</CardTitle>
                    <CardDescription>Due on: 17th Dec 2023</CardDescription>
                  </div>
                  <div className="flex items-center gap-2">
                    <CardDescription className="text-green-500">
                      Completed
                    </CardDescription>
                    <CheckIcon className="w-6 h-6 fill-green-500" />
                  </div>
                </CardHeader>
                <Button className="mt-4 bg-[#3399ff] text-white hover:bg-blue-500">{`Topics->`}</Button>
              </Card>
              <Card className="bg-white p-4 shadow-lg">
                <CardHeader>
                  <CardTitle>Operating Systems</CardTitle>
                  <CardDescription>Due on: 10th Oct 2023</CardDescription>
                </CardHeader>
                <Button className="mt-4 bg-[#3399ff] text-white hover:bg-blue-500">{`Topics->`}</Button>
              </Card>
            </div>
          </section>
          <section className="mb-6">
            <h2 className="text-xl font-semibold mb-2">Quiz</h2>
            <div className="grid grid-cols-4 gap-4">
              <Card className="bg-white p-4 shadow-lg">
                <CardHeader>
                  <CardTitle>Data Structures and Algorithms</CardTitle>
                  <CardDescription>Posted on: 20th Jan 2024</CardDescription>
                </CardHeader>
                <Button className="mt-4 bg-[#3399ff] text-white hover:bg-blue-500">
                  View Details
                </Button>
              </Card>
              <Card className="bg-white p-4 shadow-lg">
                <CardHeader>
                  <CardTitle>Computer Networks</CardTitle>
                  <CardDescription>Posted on: 15th Dec 2023</CardDescription>
                </CardHeader>
                <Button className="mt-4 bg-[#3399ff] text-white hover:bg-blue-500">
                  View Details
                </Button>
              </Card>
              <Card className="bg-white p-4 shadow-lg">
                <CardHeader>
                  <CardTitle>Operating Systems</CardTitle>
                  <CardDescription>Posted on: 10th Nov 2023</CardDescription>
                </CardHeader>
                <Button className="mt-4 bg-[#3399ff] text-white hover:bg-blue-500">
                  View Details
                </Button>
              </Card>
              <Button className="bg-gray-300 dark:bg-blue-700 text-black hover:bg-blue-500">
                Add Quiz
              </Button>
            </div>
          </section>
        </main>
      </div>
    </>
  );
}

function CheckIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <polyline points="20 6 9 17 4 12" />
    </svg>
  );
}
