/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/A28iY5ckrQF
 */
import { AvatarImage, AvatarFallback, Avatar } from "@/components/ui/avatar";
import {
  CardTitle,
  CardHeader,
  CardContent,
  CardFooter,
  Card,
} from "@/components/ui/card";
import {
  DropdownMenuTrigger,
  DropdownMenuSeparator,
  DropdownMenuItem,
  DropdownMenuContent,
  DropdownMenu,
} from "@/components/ui/dropdown-menu";
import { Swiper, SwiperSlide } from "swiper/react";
// Import Swiper styles
import "swiper/css";
import "swiper/css/navigation";
import { Navigation } from "swiper/modules";
import "./ProfessorPage.css";
import { Button } from "@/components/ui/button";
import { Progress } from "@/components/ui/progress";
import Logo from "../../../assets/Logo/logo.png";

export default function ProfessorPage({ classes }) {
  return (
    <div className="min-h-screen flex bg-gray-100">
      <aside className="w-60 bg-black text-white">
        <div className="flex flex-col items-center justify-center py-6">
          <img
            className="h-36 w-48 object-cover rounded-full cursor-pointer"
            src={Logo}
            alt=""
          />
          <span className="ml-2 font-semibold text-xl">John Doe</span>
        </div>
        <nav className="mt-7 min-h-[400px]">
          <a
            className="flex items-center px-6 py-4 text-lg font-semibold"
            href="#"
          >
            <HomeIcon className="w-6 h-6 text-[#A8ABBA]" />
            <span className="ml-4 text-[#A8ABBA]  hover:text-[#ECF0F1]">
              Home
            </span>
          </a>
          <a
            className="flex items-center px-6 py-4 text-lg font-semibold "
            href="#"
          >
            <BookIcon className="w-6 h-6 text-[#A8ABBA]" />
            <span className="ml-4 text-[#A8ABBA]  hover:text-[#ECF0F1]">
              Assigned Courses
            </span>
          </a>

          <a
            className="flex items-center px-6 py-4 text-lg font-semibold "
            href="#"
          >
            <FileEditIcon className="w-6 h-6 text-[#A8ABBA]" />
            <span className="ml-4 text-[#A8ABBA]  hover:text-[#ECF0F1]">
              Practice Questions
            </span>
          </a>
          <a
            className="flex items-center px-6 py-4 text-lg font-semibold"
            href="#"
          >
            <ListIcon className="w-6 h-6 text-[#A8ABBA]" />
            <span className="ml-4 text-[#A8ABBA]  hover:text-[#ECF0F1]">
              Student Quizzes
            </span>
          </a>
          <a
            className="flex items-center px-6 py-4 text-lg font-semibold"
            href="#"
          >
            <ActivityIcon className="w-6 h-6 text-[#A8ABBA]" />
            <span className="ml-4 text-[#A8ABBA]  hover:text-[#ECF0F1]">
              Student Assessments
            </span>
          </a>
        </nav>
      </aside>
      <main className="flex-1 p-6 overflow-auto">
        <header className="bg-white shadow mb-8">
          <div className="px-4 py-5 sm:px-6 flex justify-between items-center">
            <h1 className="text-xl font-semibold px-32 py-2 bg-[#040404] text-[#A8ABBA] rounded-md">
              Teacher Dashboard
            </h1>
            {/* <Avatar>
              <AvatarImage
                alt="Teacher profile"
                src="/placeholder.svg?height=40&width=40"
              />
              <AvatarFallback>JD</AvatarFallback>
            </Avatar> */}
            <DropdownMenu>
              <DropdownMenuTrigger asChild>
                <Avatar className="h-9 w-9">
                  <AvatarImage
                    alt="User avatar"
                    src="https://imgs.search.brave.com/J0ixr3aHGA8aitBrET8u4exc5KcrQl8PWXGrvAdsUY4/rs:fit:500:0:0/g:ce/aHR0cHM6Ly9mcmVl/c3ZnLm9yZy9pbWcv/YWJzdHJhY3QtdXNl/ci1mbGF0LTQucG5n"
                  />
                </Avatar>
              </DropdownMenuTrigger>
              <DropdownMenuContent>
                <DropdownMenuSeparator />
                <DropdownMenuItem>
                  <a className="flex items-center gap-2" href="#">
                    <UserIcon className="w-4 h-4" />
                    John Doe
                  </a>
                </DropdownMenuItem>
                <DropdownMenuItem>
                  <a className="flex items-center gap-2" href="#">
                    <MailIcon className="w-4 h-4" />
                    ums@gmail.com
                  </a>
                </DropdownMenuItem>
                <DropdownMenuSeparator />
                <DropdownMenuItem>
                  <a className="flex items-center gap-2" href="#">
                    <LogOutIcon className="w-4 h-4" />
                    Logout
                  </a>
                </DropdownMenuItem>
              </DropdownMenuContent>
            </DropdownMenu>
          </div>
        </header>
        <div className="px-4 py-5 sm:p-6">
          <section className="mb-8">
            <h2 className=" leading-6 text-gray-900 mb-2 text-2xl font-bold">
              Assigned Courses
            </h2>
            <Swiper
              navigation={true}
              modules={[Navigation]}
              className="px-3 py-3 mySwiper"
              slidesPerView={3}
              spaceBetween={30}
            >
              {classes.map((course) => (
                <SwiperSlide className=" rounded-[50px]" key={course.id}>
                  <Card className="w-full shadow-lg  rounded-[30px]">
                    <CardHeader>
                      <CardTitle>{course.title}</CardTitle>
                      {/* <CardDescription>{card.description}</CardDescription> */}
                    </CardHeader>
                    <CardContent>
                      <Progress className="w-full" value={course.value} />
                    </CardContent>
                    <CardFooter className="flex justify-between">
                      <Button variant="outline">View Details</Button>

                      <div className="bg-secondary text-secondary-foreground hover:bg-secondary/80 p-1.5 rounded-md px-2 text-[15px]">
                        <div className="flex gap-2">
                          <span className="text-[#272E3F] font-bold">
                            {course.value}%
                          </span>{" "}
                          <span className="text-[#272E3F] font-semibold">
                            Completed
                          </span>
                        </div>
                      </div>
                    </CardFooter>
                  </Card>
                </SwiperSlide>
              ))}
            </Swiper>
          </section>

          <section className="mb-8">
            <div className="flex gap-5 items-center justify-between">
              <h2 className="leading-6 text-gray-900 mb-2 text-2xl font-bold">
                Student Practice Questions
              </h2>
              <Button className="bg-[#040404] text-[#B3CCC2]">
                Create Practice Questions
              </Button>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-3 gap-4 mt-4">
              <Card className="w-full">
                <CardHeader>
                  <CardTitle>Algebra Practice</CardTitle>
                </CardHeader>
                <CardContent>
                  <p>Set of 15 Algebra Questions</p>
                </CardContent>
                <CardFooter className="flex justify-end">
                  {/* <Button>Assigned to Students</Button> */}
                  <div className="bg-[#B3CCC2] text-secondary-foreground  p-1.5 rounded-md px-2 text-[15px] flex gap-2 items-center">
                    <span className="font-semibold">Assigned</span>
                    <span>
                      <CheckCircleIcon className="w-5 h-5" />
                    </span>
                  </div>
                </CardFooter>
              </Card>
              <Card className="w-full">
                <CardHeader>
                  <CardTitle>Geometry Practice</CardTitle>
                </CardHeader>
                <CardContent>
                  <p>Set of 10 Geometry Questions</p>
                </CardContent>
                <CardFooter className="flex justify-end">
                  {/* <Button>Assign to Students</Button> */}
                  <div className="bg-[#B3CCC2] text-secondary-foreground  p-1.5 rounded-md px-2 text-[15px] flex gap-2 items-center">
                    <span className="font-semibold">Assigned</span>
                    <span>
                      <CheckCircleIcon className="w-5 h-5" />
                    </span>
                  </div>
                </CardFooter>
              </Card>
              <Card className="w-full">
                <CardHeader>
                  <CardTitle>Grammar Practice</CardTitle>
                </CardHeader>
                <CardContent>
                  <p>Set of 20 Grammar Questions</p>
                </CardContent>
                <CardFooter className="flex justify-end">
                  {/* <Button>Assign to Students</Button> */}
                  <div className="bg-[#B3CCC2] text-secondary-foreground  p-1.5 rounded-md px-2 text-[15px] flex gap-2 items-center">
                    <span className="font-semibold">Assigned</span>
                    <span>
                      <CheckCircleIcon className="w-5 h-5" />
                    </span>
                  </div>
                </CardFooter>
              </Card>
            </div>
          </section>
          <section className="mb-8">
            <div className="flex gap-5 items-center justify-between">
              <h2 className="leading-6 text-gray-900 mb-2 text-2xl font-bold">
                Quizzes
              </h2>
              <Button className="bg-[#040404] text-[#B3CCC2]">
                Create Quiz
              </Button>
            </div>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4 mt-4">
              <Card className="w-full">
                <CardHeader>
                  <CardTitle>Weekly Quiz</CardTitle>
                </CardHeader>
                <CardContent>
                  <p>10 Questions - Multiple Choice</p>
                </CardContent>
                <CardFooter className="flex justify-end">
                  {/* <Button>Assign to Students</Button> */}
                  <div className="bg-[#B3CCC2] text-secondary-foreground  p-1.5 rounded-md px-2 text-[15px] flex gap-2 items-center">
                    <span className="font-semibold">Assigned</span>
                    <span>
                      <CheckCircleIcon className="w-5 h-5" />
                    </span>
                  </div>
                </CardFooter>
              </Card>
            </div>
          </section>
          <section>
            <div className="flex gap-5 items-center justify-between">
              <h2 className="leading-6 text-gray-900 mb-2 text-2xl font-bold">
                Assessments
              </h2>
              <Button className="bg-[#040404] text-[#B3CCC2]">
                Create Assessments
              </Button>
            </div>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4 mt-4">
              <Card className="w-full">
                <CardHeader>
                  <CardTitle>Unit Test</CardTitle>
                </CardHeader>
                <CardContent>
                  <p>20 Questions - Mix of Types</p>
                </CardContent>
                <CardFooter className="flex justify-end">
                  {/* <Button>Assign to Students</Button> */}
                  <div className="bg-[#B3CCC2] text-secondary-foreground  p-1.5 rounded-md px-2 text-[15px] flex gap-2 items-center">
                    <span className="font-semibold">Assigned</span>
                    <span>
                      <CheckCircleIcon className="w-5 h-5" />
                    </span>
                  </div>
                </CardFooter>
              </Card>
            </div>
          </section>
        </div>
      </main>
    </div>
  );
}

function HomeIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m3 9 9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z" />
      <polyline points="9 22 9 12 15 12 15 22" />
    </svg>
  );
}
function BookIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M4 19.5v-15A2.5 2.5 0 0 1 6.5 2H20v20H6.5a2.5 2.5 0 0 1 0-5H20" />
    </svg>
  );
}

function CheckCircleIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M22 11.08V12a10 10 0 1 1-5.93-9.14" />
      <polyline points="22 4 12 14.01 9 11.01" />
    </svg>
  );
}

function FileEditIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M4 13.5V4a2 2 0 0 1 2-2h8.5L20 7.5V20a2 2 0 0 1-2 2h-5.5" />
      <polyline points="14 2 14 8 20 8" />
      <path d="M10.42 12.61a2.1 2.1 0 1 1 2.97 2.97L7.95 21 4 22l.99-3.95 5.43-5.44Z" />
    </svg>
  );
}

function ListIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <line x1="8" x2="21" y1="6" y2="6" />
      <line x1="8" x2="21" y1="12" y2="12" />
      <line x1="8" x2="21" y1="18" y2="18" />
      <line x1="3" x2="3.01" y1="6" y2="6" />
      <line x1="3" x2="3.01" y1="12" y2="12" />
      <line x1="3" x2="3.01" y1="18" y2="18" />
    </svg>
  );
}
function UserIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M19 21v-2a4 4 0 0 0-4-4H9a4 4 0 0 0-4 4v2" />
      <circle cx="12" cy="7" r="4" />
    </svg>
  );
}

function MailIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect width="20" height="16" x="2" y="4" rx="2" />
      <path d="m22 7-8.97 5.7a1.94 1.94 0 0 1-2.06 0L2 7" />
    </svg>
  );
}

function LogOutIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M9 21H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h4" />
      <polyline points="16 17 21 12 16 7" />
      <line x1="21" x2="9" y1="12" y2="12" />
    </svg>
  );
}
function ActivityIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M22 12h-4l-3 9L9 3l-3 9H2" />
    </svg>
  );
}
