/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/PZEUK21WTPE
 */
import {
  CollapsibleTrigger,
  CollapsibleContent,
  Collapsible,
} from "@/components/ui/collapsible";
import {
  DropdownMenuTrigger,
  DropdownMenuLabel,
  DropdownMenuSeparator,
  DropdownMenuItem,
  DropdownMenuContent,
  DropdownMenu,
} from "@/components/ui/dropdown-menu";
import { AvatarImage, AvatarFallback, Avatar } from "@/components/ui/avatar";
import { Button } from "@/components/ui/button";
import { Link } from "react-router-dom";
<<<<<<< HEAD

=======
import unitData from "../../../assets/units.json";
>>>>>>> 7838443ae18e078f9ce1879dd21e40befd838f28
import Logo from "../../../assets/Logo/logo.png";
import gsap from "gsap";
import { useGSAP } from "@gsap/react";
import { useRef } from "react";
<<<<<<< HEAD
import { useParams } from "react-router-dom";

export default function Detailspage({ classes }) {
  const { subject } = useParams();

  const selectedClass = classes.find((c) => c.title.toLowerCase() === subject);
  if (!selectedClass) {
    return <div>Class not found!</div>;
  }

=======
export default function Detailspage() {
>>>>>>> 7838443ae18e078f9ce1879dd21e40befd838f28
  const imgRef = useRef(null);
  const subRef = useRef(null);
  const profRef = useRef(null);

  useGSAP(() => {
    var tl = gsap.timeline();

    tl.from([imgRef.current, profRef.current], {
      y: -100,
      duration: 0.5,
      stagger: 0.3,
    });
    tl.from(subRef.current, {
      y: 100,
      opacity: 0,
      duration: 0.5,
    });
  });

  return (
    <div className="flex items-center bg-[#040404] min-h-screen relative flex-col justify-start gap-4">
<<<<<<< HEAD
      <div className="flex flex-col items-center justify-start w-full mt-16">
        <header className="flex items-center h-16 mb-5 dark:bg-gray-900  sticky top-5 z-[1] w-full">
=======
      <div className="flex items-center justify-start flex-col w-full">
        <header className="flex items-center h-16 mb-5 dark:bg-gray-900 mt-5 relative w-full">
>>>>>>> 7838443ae18e078f9ce1879dd21e40befd838f28
          <nav className="flex items-center justify-between w-[100%] p-10">
            <div className="flex gap-4" ref={imgRef}>
              <div className=" h-[100px] w-[100px] flex items-center justify-center relative overflow-hidden">
                <Link to="/studentui">
                  <img
<<<<<<< HEAD
                    className="object-cover cursor-pointer "
=======
                    className=" object-cover cursor-pointer"
>>>>>>> 7838443ae18e078f9ce1879dd21e40befd838f28
                    src={Logo}
                    alt=""
                  />
                </Link>
              </div>

              <div className="flex items-center space-x-4">
<<<<<<< HEAD
                <span className="text-xl font-semibold  py-2 bg-[#040404] text-[#B3CCC2] rounded-md ">
                  YOUR CLASSROOM
=======
                {/* <LayoutDashboardIcon className="w-6 h-6" /> */}
                <span className="text-xl font-semibold  py-2 bg-[#040404] text-[#B3CCC2] rounded-md ">
                  Your Classroom
>>>>>>> 7838443ae18e078f9ce1879dd21e40befd838f28
                </span>
              </div>
            </div>
            <div ref={profRef}>
              <DropdownMenu>
                <DropdownMenuTrigger asChild>
                  <Avatar className="h-9 w-9">
                    <AvatarImage
                      alt="User avatar"
                      src="https://imgs.search.brave.com/J0ixr3aHGA8aitBrET8u4exc5KcrQl8PWXGrvAdsUY4/rs:fit:500:0:0/g:ce/aHR0cHM6Ly9mcmVl/c3ZnLm9yZy9pbWcv/YWJzdHJhY3QtdXNl/ci1mbGF0LTQucG5n"
                    />
<<<<<<< HEAD
=======
                    {/* <AvatarFallback>JD</AvatarFallback> */}
>>>>>>> 7838443ae18e078f9ce1879dd21e40befd838f28
                  </Avatar>
                </DropdownMenuTrigger>
                <DropdownMenuContent>
                  <DropdownMenuSeparator />
                  <DropdownMenuItem>
                    <a className="flex items-center gap-2" href="#">
                      <UserIcon className="w-4 h-4" />
                      John Doe
                    </a>
                  </DropdownMenuItem>
                  <DropdownMenuItem>
                    <a className="flex items-center gap-2" href="#">
                      <MailIcon className="w-4 h-4" />
                      ums@gmail.com
                    </a>
                  </DropdownMenuItem>
                  <DropdownMenuSeparator />
                  <DropdownMenuItem>
                    <a className="flex items-center gap-2" href="#">
                      <LogOutIcon className="w-4 h-4" />
                      Logout
                    </a>
                  </DropdownMenuItem>
                </DropdownMenuContent>
              </DropdownMenu>
            </div>
          </nav>
        </header>
<<<<<<< HEAD

        {/* Here it starts Subject content which contains units or Topics */}

=======
>>>>>>> 7838443ae18e078f9ce1879dd21e40befd838f28
        <div
          key="1"
          className="flex flex-col gap-6 p-10 w-[95%] border rounded-[30px] bg-[#fff]"
          ref={subRef}
        >
          <div className="flex items-center justify-between mb-4">
<<<<<<< HEAD
            <h1 className="text-4xl font-bold">{selectedClass.title}</h1>
=======
            <h1 className="text-4xl font-bold">Mathematics</h1>
>>>>>>> 7838443ae18e078f9ce1879dd21e40befd838f28
            <p className="text-xl font-semibold">
              Estimated Completion : 8 weeks
            </p>
          </div>
<<<<<<< HEAD
          <hr className="mb-2 border-2 border-gray-500 dark:border-gray-800" />

          {selectedClass.units.map((unit) => (
            <Collapsible
              className="border border-[#494b55] rounded-lg dark:border-gray-800 relative bg-[#ECF0F1]"
              key={unit.id}
=======
          <hr className="border-2 border-gray-500 dark:border-gray-800 mb-2" />

          {unitData.map((unit, index) => (
            <Collapsible
              className="border border-[#494b55] rounded-lg dark:border-gray-800 relative bg-[#ECF0F1]"
              key={index}
>>>>>>> 7838443ae18e078f9ce1879dd21e40befd838f28
            >
              <CollapsibleTrigger asChild className="relative">
                <div className="flex items-center justify-between p-4">
                  <div className="flex items-center gap-4">
<<<<<<< HEAD
                    <h2 className="text-xl font-semibold">{unit.name}</h2>
=======
                    <h2 className="text-xl font-semibold">
                      Unit-{unit.id} : {unit.unit}
                    </h2>
>>>>>>> 7838443ae18e078f9ce1879dd21e40befd838f28
                  </div>
                  <ChevronDownIcon className="w-5 h-5 text-gray-500 dark:text-gray-400" />
                </div>
              </CollapsibleTrigger>

              <CollapsibleContent>
                <div className="flex justify-start gap-2 p-4">
<<<<<<< HEAD
                  <Link
                    to={`/practicepage/${subject}/${unit.name.toLowerCase()}`}
                  >
=======
                  <Link to="/practicepage">
>>>>>>> 7838443ae18e078f9ce1879dd21e40befd838f28
                    <Button
                      className="inline-flex items-center gap-2 text-sm font-medium bg-[#040404] text-[#B3CCC2] hover:bg-[#B3CCC2] hover:text-[#040404]  w-[150px]"
                      download
                      href="/unit-1.pdf"
                    >
                      Practice Questions
                    </Button>
                  </Link>
<<<<<<< HEAD
                  <Link to={`/quizpage/${subject}/${unit.name.toLowerCase()}`}>
=======
                  <Link to="/quizpage">
>>>>>>> 7838443ae18e078f9ce1879dd21e40befd838f28
                    {" "}
                    <Button
                      className="inline-flex items-center gap-2 text-sm font-medium bg-[#B3CCC2] text-[#040404] hover:bg-[#040404] hover:text-[#B3CCC2] w-[150px]"
                      href="/unit-1-quiz"
                    >
                      Quiz
                    </Button>
                  </Link>
                </div>
              </CollapsibleContent>
            </Collapsible>
          ))}
        </div>
      </div>
    </div>
  );
}

<<<<<<< HEAD
//These below are the used Icons in the above code

=======
>>>>>>> 7838443ae18e078f9ce1879dd21e40befd838f28
function ChevronDownIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m6 9 6 6 6-6" />
    </svg>
  );
}

function UserIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M19 21v-2a4 4 0 0 0-4-4H9a4 4 0 0 0-4 4v2" />
      <circle cx="12" cy="7" r="4" />
    </svg>
  );
}

function MailIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect width="20" height="16" x="2" y="4" rx="2" />
      <path d="m22 7-8.97 5.7a1.94 1.94 0 0 1-2.06 0L2 7" />
    </svg>
  );
}

function LogOutIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M9 21H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h4" />
      <polyline points="16 17 21 12 16 7" />
      <line x1="21" x2="9" y1="12" y2="12" />
    </svg>
  );
}
<<<<<<< HEAD

//  View Details Page Ends Here.
=======
>>>>>>> 7838443ae18e078f9ce1879dd21e40befd838f28
