/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/o6JTeuwM9Y6
 */
import { Button } from "@/components/ui/button"
import { DropdownMenuTrigger, DropdownMenuItem, DropdownMenuGroup, DropdownMenuContent, DropdownMenu } from "@/components/ui/dropdown-menu"

export default function Dropdown() {
  return (
    (<DropdownMenu>
      <DropdownMenuTrigger asChild className="text-[#040404] bg-[#ECF0F1] hover:text-[#5a5659]">
        <Button variant="outline">Select Subject</Button>
      </DropdownMenuTrigger>
      
      <DropdownMenuContent className="w-56 transition-all duration-200 ease-in-out">
        <DropdownMenuGroup>
          <DropdownMenuItem className="text-[#040404]">Maths</DropdownMenuItem>
          <DropdownMenuItem className="text-[#040404]">Digital Logic Design</DropdownMenuItem>
          
        </DropdownMenuGroup>
      </DropdownMenuContent>
    </DropdownMenu>)
  );
}
