/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/lTrMUX55ROa
 */
import { CardTitle, CardDescription, CardHeader, CardContent, Card } from "@/components/ui/card"
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"
import {Link} from "react-router-dom"

export default function Pswdreset() {
  return (
    (<main
      className="flex items-center justify-center h-screen bg-gray-100 dark:bg-gray-900">
      <Card className="w-full max-w-md px-4 py-8">
        <CardHeader className="mb-4">
          <CardTitle className="text-2xl font-bold text-center">Forgot Password</CardTitle>
          <CardDescription className="text-center text-gray-500 dark:text-gray-400">
            Enter your email below and we'll send you a link to reset your password.
          </CardDescription>
        </CardHeader>
        <CardContent>
          <form className="space-y-4">
            <div className="space-y-2">
              <Label htmlFor="email" className="font-bold">Email</Label>
              <Input id="email" placeholder="ums@example.com" required type="email" />
            </div>
            <Button className="w-full" type="submit">
              Request reset link
            </Button>
          </form>
          <div className="mt-4 text-sm text-center">
            Remembered your password? {' '}

            <Link to="/login" className="text-blue-500 underline"> Go back to login</Link>
          </div>
        </CardContent>
      </Card>
    </main>)
  );
}
