/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/w9gsS6YM8gD
 */

import React from "react";
import { useParams } from "react-router-dom";
import PracticeDynamic from "@/components/ui/PracticeDynamic";

export default function Question({ classes }) {
  const { subject } = useParams();
  const { unit } = useParams();
  const selectedClass = classes.find((c) => c.title.toLowerCase() === subject);
  const selectedUnit = selectedClass.units.find(
    (u) => u.name.toLowerCase() === unit
  );

  return (
    <div>
      <PracticeDynamic
        operator={selectedUnit.operator}
        topic={selectedUnit.name}
      />
    </div>
  );
}
